### ISSUE TITLE
menuconfig does not work on fresh clone

### ISSUE THREAD

**Issue by jean-marc-LACROIX** [sbxg/sbxg#1]
After running following command :
`git clone https://github.com/sbxg/sbxg
`
Launching first command `make menuconfig` does not work as in following log:

```
lacroix@vm-jessie-x86-amd64-3:/tmp/sbxg$ make menuconfig/
*make: Nothing to be done for 'menuconfig/
```

About my configuration....
lacroix@vm-jessie-x86-amd64-3:~$ uname -a
`Linux vm-jessie-x86-amd64-3 3.16-2-amd64 #1 SMP Debian 3.16.3-2 (2014-09-20) x86_64 GNU/Linux
`
lacroix@vm-jessie-x86-amd64-3:~$ cat /etc/debian_version 
8.3
and all process running in one LXC container
lacroix@vm-jessie-x86-amd64-3:~$ make --version

```
GNU Make 4.0
Construit pour x86_64-pc-linux-gnu
Copyright (C) 1988-2013 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>
Ceci est un logiciel libre : vous êtes autorisé à le modifier et à la redistribuer.
Il ne comporte AUCUNE GARANTIE, dans la mesure de ce que permet la loi.
lacroix@vm-jessie-x86-amd64-3:~$ 

```

**Comment by jeanguyomarch** [comment]
I can see you have written `make menuconfig/` instead of `make menuconfig`. I think it might be the reason why it does not work.
