### ISSUE TITLE
can't open file "/local_home/local/git/SBXG/sbxg.git/build/conf/kernel.cfg"

### ISSUE THREAD

**Issue by jean-marc-LACROIX** [sbxg/sbxg#12]
when i merge your branch remotes/origin/devs/jean/menuconfig in my working branch (devs/jeanmarc/kernel-4.7-integration-sbxg), it seems not possible to run 'make menuconfig' in my working dir because : 
local@solo:~/git/SBXG/sbxg.git$ git log
commit 05ddef71897b2f79b8fd025f7c423f1960d5ad14
Merge: 7b9b3cb 16924e5
Author: Jean Marc LACROIX jeanmarc.lacroix@free.fr
Date:   Thu Sep 8 11:25:33 2016 +0200

```
Merge remote-tracking branch 'remotes/origin/devs/jean/menuconfig' into devs/jeanmarc/kernel-4.7-integration-sbxg
```

local@solo:~/git/SBXG/sbxg.git$ make menuconfig
-- Configuring done
-- Generating done
-- Build files have been written to: /local_home/local/git/SBXG/sbxg.git/build/menuconfig
make[1]: Entering directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
make[2]: Entering directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
make[3]: Entering directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
make[3]: Leaving directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
[ 11%] Built target zconf
make[3]: Entering directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
make[3]: Leaving directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
[ 22%] Built target conf
make[3]: Entering directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
make[3]: Leaving directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
[ 88%] Built target lxdialog
make[3]: Entering directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
make[3]: Leaving directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
[100%] Built target mconf
make[2]: Leaving directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
make[1]: Leaving directory '/local_home/local/git/SBXG/sbxg.git/build/menuconfig'
build/conf/openconf.cfg:35: can't open file "/local_home/local/git/SBXG/sbxg.git/build/conf/kernel.cfg"
make/menuconfig.mk:71: recipe for target 'menuconfig' failed
make: **\* [menuconfig] Error 1

Thanks in advance for your help

**Comment by jeanguyomarch** [comment]
I cannot reproduce the problem. Seems like the menuconfig got lost with dependencies when you got my changes in what i suppose is a non-clean tree. Try cleaning-up your repository with a git clean or a make clean.

**Comment by jeanguyomarch** [comment]
I think this has been fixed. Please reopen if uncountered again.
