### ISSUE TITLE
Missing libssl-dev in package requirements & make install-deps

### ISSUE THREAD

**Issue by Jerome-Maurin** [sbxg/sbxg#15]
With Jean-Marc's kernel configuration using the signing functionalities in the kernel (like in the cubietruck 4.8.7 for example) the debian package libssl-dev is needed during the kernel compilation (openssl/opensslv.h & openssl/bio.h includes for example).
The README could be changed as well as the "make install-deps" to correct this.

**Comment by jeanguyomarch** [comment]
Thanks for the info.
