### ISSUE TITLE
Suggestion: add choice in menuconfig in order to use debian arm kernel package

### ISSUE THREAD

**Issue by Jerome-Maurin** [sbxg/sbxg#16]
In december 2016 debian proposes an arm kernel debian package:
https://packages.debian.org/jessie/linux-image-armmp-lpae

This could be an plus for sbxg, in order to speed up intergration & build.

The proposal would be to modifiy the menuconfig in order to add the choice between building the kernel or using debian's one.

As most of the supported platform by sbxg at the time of this suggestion, linux-image-armmp-lpae appears to be the best choice given that most (except imx6) support lpae.

This proposal was done by JML and myself.

However to be able to use this kernel, the u-boot configuration should support the boot with initrd.

This example works on the Cubietruck:

```
root@cubietruck:~# cat /boot/boot.cmd
setenv bootargs console=ttyS0,115200 earlyprintk hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x1024p60 root=/dev/mmcblk0p1 rootwait panic=10 ${extra} 
ext2load mmc 0 0x42000000 boot/zImage
ext2load mmc 0 0x43000000 boot/sun7i-a20-cubietruck.dtb
ext2load mmc 0 0x43300000 boot/initrd
bootz 0x42000000 0x43300000 0x43000000

root@cubietruck:~# uname -a
Linux cubietruck 4.8.0-1-armmp-lpae #1 SMP Debian 4.8.7-1 (2016-11-13) armv7l GNU/Linux

root@cubietruck:~# mkimage -C none -A arm -T script -d boot.cmd boot.scr
Image Name:   
Created:      Thu Nov 17 22:15:21 2016
Image Type:   ARM Linux Script (uncompressed)
Data Size:    1918 Bytes = 1.87 kB = 0.00 MB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 1910 Bytes = 1.87 kB = 0.00 MB
```

For this to work seamlessly the package initramfs-tools should be added for the hook in dpkg, and u-boot-tools for the mkimage command.

**Comment by jeanguyomarch** [comment]
Hi Jérôme,

I do agree on that having the possibility to install a pre-build kernel instead of building one from scratch would be a great feature 👍 .

From an implementation perspective, I think we should not "impose" `linux-image-armmp-lpae`, as this is only for armv7: it should be a board-specific choice. So, we can propose something else for other architectures. Board-specific configuration items reside in the `boards` repository, and files like `Cubietruck.conf` could have new parameters (naming can probably be much better):

```bash
CONFIG_DEFAULT_DEBIAN_KERNEL="linux-image-3.16.0-4-armmp-lpae"
CONFIG_DEFAULT_DEBIAN_INITRD="boot/uinitrd"
CONFIG_DEFAULT_DEBIAN_IMAGE="boot/zImage"
``` 
I'm not quite sure yet how to nicely handle the generation of the u-boot script: should we make one template or two different ones? I feel like the `uboot.cmd.in` should not have been a common file, but provided by the boards repository...

> root@cubietruck:~# uname -a
> Linux cubietruck 4.8.0-1-armmp-lpae #1 SMP Debian 4.8.7-1 (2016-11-13) armv7l GNU/Linux

I don't quite understand why the uname says your kernel is 4.8.0-1-armmp-lpae. I though that it was 3.16 (https://packages.debian.org/jessie/linux-image-armmp-lpae).

> For this to work seamlessly the package initramfs-tools should be added for the hooks in dpkg

Mhh... I don't get why. Is it because the initramfs (/boot/uinitrd) is generated when installing the kernel? If so, it seems like initramfs-tool would be mandatory, and therefore be a dependency of the kernel package. Anyway, I guess we can just remove it after installing the kernel.

> u-boot-tools for the mkimage command

SBXG already does the mkimage, and it is the responsability of the developer to have mkimage installed in his environment. Why would the built system need that?

I don't know if you already started to implement that, or if have planned it. If so, I would be very happy if you could submit a pull request. Otherwise, it could take some time to get in, as I'm a little bit overwhelmed by other things at the moment.

**Comment by Jerome-Maurin** [comment]
I agree with you concerning the multiple kernels to support every arch, by doing a board-pecific configuration.

What do you mean by the u-boot script ? The source of the boot.scr on the root file-system ?

The reason my uname -a says 4.8.0-1-armmp-lpae, is that I built a stretch rootfs.

The initramfs-tool package is not a dependency of the kernel package in my use-case (stretch) so I had to add it manually.
It is needed if you want to easily build an initramfs, which I did, because being a "generic" Debian kernel (supposed to be able to boot on a large number of platforms) the linux-image-armmp-lpae has a lot of modules, included some needed to boot from the sdcard (accessing the rootfs).
Furthermore I believe the package initramfs-tool should be kept installed, because in the event of an update for the kernel package, the initramfs should be updated as well, and as the kernel package has a dpkg post-install hook to update-initramfs, this is done automatically at the end of the kernel update.

The way I load a iniramfs in u-boot is with either the bootz or bootm, as second parameter.
It seams that a simple initramfs is not enough, you need to wrap it with mkimage, which should be therefor added if you want your system to auto-update yourn initramfs when the kernel is updated.

I haven't implemented anything yet concerning this issue, if I do I'll let you know and do a pull request.

**Comment by Jerome-Maurin** [comment]
Hi,

to continue on the kernel packages choice, using "linux-image-armmp-lpae" for armv7 and "linux-image-arm64" for armv8 should be enough for the moment, considering the boards listed in the "boards" repository.

**Comment by jeanguyomarch** [comment]
> What do you mean by the u-boot script ? The source of the boot.scr on the root file-system ?

Yes.

Okay, adding and keeping `initramfs-tools` and `mkimage` seems to make sense to me after your explaination.

**Comment by Jerome-Maurin** [comment]
After a little research the bootz command in u-boot can be used as follows:

bootz KERNEL_ADDR INITRAMFS_ADDR:SIZE_OF_INITRAMFS DTB_ADDR

which means we do not need the mkimage on the target rootfs.

For example for a cubietruck we can use:

ext2load mmc 0 0x42000000 boot/zImage
ext2load mmc 0 0x43000000 boot/sun7i-a20-cubietruck.dtb
ext2load mmc 0 0x43300000 boot/initrd
bootz 0x42000000 0x43300000:${filesize} 0x43000000

because the environment variable "filesize" is set by ext2load;
so provided we call ext2load on the initrd last before the bootz call,
"filesize" will contain the size of the initrd, which means a simple initrd can be used and mkimage is no longer needed.

Of course all this is only true with the use of a recent enough version of u-boot, where the zboot command is available

**Comment by Jerome-Maurin** [comment]
To sum up here is an example boot.cmd file for Cubietruck with comments by Jean-Marc & me:

```
# Boot script for a zImage with an inirtd

# In order to 'compile', please enter :
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr

# Requirements for this script to work (you can use symbolic links to point to the correct file) :
# - recent enough u-boot to support the bootz command
# - Kernel using the zImage format at /boot/zImage
# - Initrd using the initramfs format at /boot/initrd
#   (example for debian the update-initramfs command can be used to create it)
# - DTB using the device-tree binary format provided by the kernel at /boot/dtb
#   (for example, if using a Debian Kernel package, look for the dtb
#   corresponding to your board in /usr/lib/KERNEL_NAME/)

# Set the Linux bootargs
setenv bootargs console=ttyS0,115200 earlyprintk hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x1024p60 root=/dev/mmcblk0p1 rootwait panic=10 ${extra}

# Load the zImage
ext2load mmc 0 0x42000000 boot/zImage

# Load the DTB
ext2load mmc 0 0x43000000 boot/dtb

# Load the initrd last to have the correct value set in ${filesize} set by the
# ext2load command
ext2load mmc 0 0x43300000 boot/initrd

# Boot from the zImage with the initrd using the correct size from ${filesize}
# and the DTB
bootz 0x42000000 0x43300000:${filesize} 0x43000000
```

**Comment by jeanguyomarch** [comment]
SBXG shifted its scope a bit with v2. It does not touch the rootfs anymore, we just generate "factory" images. If one want to use armbian packages, this would require rootfs provisionning, which is not handled by SBXG.
